"""add last_read_at to conversation_members

Revision ID: a241debd12b7
Revises: d569fa7540f7
Create Date: 2026-03-14 21:17:04.046079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a241debd12b7'
down_revision: Union[str, Sequence[str], None] = 'd569fa7540f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_members', sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_members', 'last_read_at')
    # ### end Alembic commands ###
